import "./globals.css";
//import styles from "./layout.module.css";
import Navbar from "@/components/Navbar";
import Nav from "@/components/Nav";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BMET App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex flex-col bg-[#460305]">
          <div>
            <Nav />
          </div>
          <div className="flex justify-center">
            <Image
              src="/images/TitleBanner.gif"
              alt="logo"
              width={800}
              height={300}
            ></Image>
          </div>
          <div>
            <Navbar />
          </div>
        </header>

        <div>{children}</div>
      </body>
    </html>
  );
}
